### PR TITLE
Remove libcurl dependency

### PR DESCRIPTION
**Pull request by jjerphan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Unix builds need not depends on libcurl:
 - https://github.com/HowardHinnant/date/blob/6e921e1b1d21e84a5c82416ba7ecd98e33a436d0/CMakeLists.txt#L154-L158
 - https://github.com/conda-forge/howardhinnant_date-feedstock/blob/091f6a237251ffbbbfa68f2ce7f440ea3d8088a7/recipe/build.sh#L16

Also [libcurl properly encodes runtime requirements](https://github.com/conda-forge/curl-feedstock/blob/3d6c4469eb66a73b74f9f457b7a63f8713829354/recipe/meta.yaml#L47-L49
), so its presence in the `run` section is not required.

### CODE REVIEW

**Comment by pidefrem** [comment]
Hello @jjerphan. The condition for the unix build dependency on libcurl is:
```
 if( NOT USE_SYSTEM_TZ_DB AND NOT MANUAL_TZ_DB )
```

In the `build.sh` file, 
```
cmake -DCMAKE_INSTALL_PREFIX=$PREFIX $SRC_DIR -DCMAKE_INSTALL_LIBDIR=lib -DBUILD_SHARED_LIBS=ON -DUSE_SYSTEM_TZ_DB=ON -DBUILD_TZ_LIB=ON -DCMAKE_CXX_FLAGS="-fPIC" -DCMAKE_BUILD_TYPE=Release $CMAKE_CXX_FLAGS
```

the `DUSE_SYSTEM_TZ_DB` is indeed set to `ON`.

**Review by pidefrem — APPROVED** [review]

**Review by pidefrem — COMMENTED** [review]
Hello @jjerphan. The condition for the unix build dependency on libcurl is:
```
 if( NOT USE_SYSTEM_TZ_DB AND NOT MANUAL_TZ_DB )
```
In the build.sh file,
```
cmake -DCMAKE_INSTALL_PREFIX=$PREFIX $SRC_DIR -DCMAKE_INSTALL_LIBDIR=lib -DBUILD_SHARED_LIBS=ON -DUSE_SYSTEM_TZ_DB=ON -DBUILD_TZ_LIB=ON -DCMAKE_CXX_FLAGS="-fPIC" -DCMAKE_BUILD_TYPE=Release $CMAKE_CXX_FLAGS
```
the `DUSE_SYSTEM_TZ_DB` is indeed set to ON.
The option is `ON` as well for the windows build.

How do you justify keeping the dependency for windows if you remove it for unix?

**Comment by jjerphan** [comment]
Hi @pidefrem 

Thank you for making this observation.

The dependency might also be removed for Windows, indeed.

To be fair with you, I have not looked into that further as the project I work only depends on this library on unix (effectively when it is built against libcpp).

I am currently off, but I may have a look then. Feel free to modify this PR or merge it.

**Review by pidefrem — APPROVED** [review]

**Comment by jjerphan** [comment]
I believe the dependency on `libcurl` for Windows was meant to use the network due to https://github.com/HowardHinnant/date/issues/788 and similar other issues.

**Comment by jjerphan** [comment]
Actually https://github.com/HowardHinnant/date/pull/611.

**Pull request merged**
